### ISSUE TITLE
Idea: Optional ability to deploy a test VM in the private cloud

### ISSUE THREAD

**Issue by xelizondo** [Azure/Enterprise-Scale-for-AVS#105]
Similar to the jumpbox VM, customers have asked, would it be possible to include an option to create a test VM (greenfield first then Brownfield) for testing traffic flow connectivity. Either Windows/Linux VM as long as you can do probing, traceroute/tracert, curl, ping, probing open ports (like Test-NetConnection). 

This may be dependent on or will require automating first:

1. The creation of a DHCP profile in NSX
2. Associating the DHCP profile to the T1 gateway
3. The creation of a network segment for the VM/workload
4. Creating a content library in vCenter 
5. Importing an OVA file to the library as a template
6. Deploying a new VM using the OVA template

**Comment by prasad3017** [comment]
@xelizondo We have added this Jul sprint 

@jchancellor-ms  has built Terraform code for this. COuld you please share?

**Comment by prasad3017** [comment]
@xelizondo  We have this option we have developed. Khush is working toward pushing it Nov or Dec 2022

**Comment by prasad3017** [comment]
Hello @xelizondo  This is available via TF for the customers. PLease feel free to open the request again
