### ISSUE TITLE
Fix: Terraform - Re-applying private cloud attempts re-creation

### ISSUE THREAD

**Issue by jchancellor-ms** [Azure/Enterprise-Scale-for-AVS#106]
Sensitive values in the private cloud configuration force replacement when re-running terraform apply.  
![tf-apply-issue](https://user-images.githubusercontent.com/84210452/163219226-7846f2b2-8593-49fa-91d2-cef901b85e29.png)

**Comment by prasad3017** [comment]
@jchancellor-ms  Resolving this but please re-open if needed
