### ISSUE TITLE
Idea: AVS Landing Zone Accelerator to be made available from inside of Azure Portal

### ISSUE THREAD

**Issue by Mahesh-MSFT** [Azure/Enterprise-Scale-for-AVS#111]
It is observed that AVS private cloud is deployed from "inside" of Azure portal. When deployed this way, AVS Landing Zone Accelerator doesn't appear as an option. This results in AVS deployment that is not aligned with AVS best practices recommended through AVS Landing Zone Accelerator.

**Comment by prasad3017** [comment]
Hello Mahesh,

Let me know if we can close this.

**Comment by prasad3017** [comment]
@Mahesh-MSFT  This is something we will track internally and looking for help

**Comment by Mahesh-MSFT** [comment]
closing this as its accepted as backlog now!
