### ISSUE TITLE
Idea: Deploy additional Terraform Modules for deployment scenarios

### ISSUE THREAD

**Issue by jchancellor-ms** [Azure/Enterprise-Scale-for-AVS#126]
Adding an issue for additional terraform work being completed to support the variety of deployment scenarios for AVS.  Preference for getting deployments aligned with the Landing Zone network scenarios.

**Comment by prasad3017** [comment]
@jchancellor-ms  can we close this?

**Comment by jchancellor-ms** [comment]
Added multiple Scenarios and modules with documentation.  Will continue to create new scenarios and samples.
