### ISSUE TITLE
Idea: AVS Workbook - Add Private Cloud as Filter

### ISSUE THREAD

**Issue by suellenferreira** [Azure/Enterprise-Scale-for-AVS#161]
Evaluate the possibility to Add "Private Cloud" as Filter on the top of the Workbook. At this moment the data showing at the menus "Summary, Resources, VMs, Alerts, Advisor and Activity" are aggregating data from all the existing Private Clouds of a Subscription. It would be great if we could select only the Private Cloud we want to see the Logs.

**Comment by prasad3017** [comment]
@shaunjacob  could you please check this?

**Comment by prasad3017** [comment]
@WKahnZA  Could you please check on this. @fskelly  if you could look into this too?

**Comment by WKahnZA** [comment]
Adding filters for October sprint

**Comment by prasad3017** [comment]
Thank you

**Comment by prasad3017** [comment]
Resolving this
