### ISSUE TITLE
Connect AVS to a new virtual network - Failed

### ISSUE THREAD

**Issue by sblair01** [Azure/Enterprise-Scale-for-AVS#172]
Didn't recognize my sub:  https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2FEnterprise-Scale-for-AVS%2Fmain%2FBrownField%2FNetworking%2FAVS-to-VNet-NewVNet%2FARM%2FVNetWithExR.deploy.json

{
  "code": "SubscriptionNotFound",
  "message": "The subscription '/subscriptions/ed0a3e52-X-X' could not be found."
}

**Comment by seanluce** [comment]
All instances of subscription().Id need to be changed to subscription().subscriptionId

see here: https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/bicep-functions-scope#return-value-2

**Comment by prasad3017** [comment]
@sblair01  please let us know if you are still having issues.

**Comment by prasad3017** [comment]
@sblair01  please check and let me know

**Comment by sblair01** [comment]
@fskelly is this a flag we can make permanent in the bicep so that I don't have to manually populate it,

**Comment by jchancellor-ms** [comment]
Corrected this in the ARM template in pull request https://github.com/Azure/Enterprise-Scale-for-AVS/pull/194.  @prasad3017 and @sblair01. I've tested the ARM deployment and this is working now.  Please let me know if you need me to re-open and fix anything else.
