### ISSUE TITLE
HCX Cloud Deployment

### ISSUE THREAD

**Issue by vmarcs** [Azure/Enterprise-Scale-for-AVS#180]
Since longer time, MS removed the HCX Cloud Deployment from this base deployment of AVS.
At the moment there is not terraform option to deploy HCX Cloud within AVS.

Is there anything planned or a workaround ?

**Comment by sblair01** [comment]
Thank you @vmarcs for the submission. Let me sync this with the internal team and get back to you with a response. Please allow 72hours latest for processing.

**Comment by prasad3017** [comment]
@vmarcs in the product we still have option of HCX under Add-ons?
Also, please check our green field deployment where we provide Add-on option to deploy https://github.com/Azure/Enterprise-Scale-for-AVS/blob/main/AVS-Landing-Zone/GreenField/readme.md

Could you please share if this helps?

**Comment by vmarcs** [comment]
Hi,
you are right - for automated deployment over biceps ([AVSAddons.bicep](https://github.com/Azure/Enterprise-Scale-for-AVS/blob/main/AVS-Landing-Zone/GreenField/Bicep/Modules/AVSAddons.bicep))

I want to do the "full" deployment over "Terraform" so I looking for the same in "terraform" like the script for addon in bicep. 
Hopefully it is clear what I mean.

**Comment by vmarcs** [comment]
Hi,

2 things we need for more automation:
1. Deployment of HCX over TF 
2. Create a "onpem" HCX key in HCX-Addon for onprem - save the key to an variable ... for the onprem HCX automated install.

**Comment by prasad3017** [comment]
Thank you @vmarcs . Did you already try deploying AVS using TF modules from the Git repo?

CC: @jchancellor-ms

**Comment by prasad3017** [comment]
@jchancellor-ms  Could you please check and provide a status on this.

**Comment by vmarcs** [comment]
Which one do you mean?

Von: prasad3017 ***@***.***>
Datum: Donnerstag, 10. November 2022 um 23:03
An: Azure/Enterprise-Scale-for-AVS ***@***.***>
Cc: Marc Sauter ***@***.***>, Mention ***@***.***>
Betreff: Re: [Azure/Enterprise-Scale-for-AVS] HCX Cloud Deployment (Issue #180)
!! External Email

Thank you @vmarcs<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvmarcs&data=05%7C01%7Cmarcs%40vmware.com%7C1345374b6e0b4cfeb47608dac367607f%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C638037146053552344%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=U3%2B0hQMWHtjS5Q6RTo6nrqtp4GSy6rQ%2F7TaIV9kT6vs%3D&reserved=0> . Did you already try deploying AVS using TF modules from the Git repo?

CC: @jchancellor-ms<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjchancellor-ms&data=05%7C01%7Cmarcs%40vmware.com%7C1345374b6e0b4cfeb47608dac367607f%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C638037146053552344%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=h5oBuBTsGDDtVTq1EzYhDYDMQPte6wOz2eVtec4z82c%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2FEnterprise-Scale-for-AVS%2Fissues%2F180%23issuecomment-1310962091&data=05%7C01%7Cmarcs%40vmware.com%7C1345374b6e0b4cfeb47608dac367607f%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C638037146053552344%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=dsa%2FtRx7HcKr%2FcS4khEcPslxbOgodZjCAFcmZVLapbY%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FATSXT6YBBIDD76NB74ZBMETWHVWKPANCNFSM6AAAAAAR4QIVL4&data=05%7C01%7Cmarcs%40vmware.com%7C1345374b6e0b4cfeb47608dac367607f%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C638037146053552344%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=PKXeABAVGk6eYsKusPMpRCPMXdQOe7oiL4zTNAEUmxo%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

!! External Email: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender.

**Comment by vmarcs** [comment]
I deployed AVS using TF several times, also backend config with Hub and global reach connection to AVS.

I am still searching for deploying the "AddON" over "Terraform"

**Comment by jchancellor-ms** [comment]
@vmarcs - I've added modules for the HCX add_on with an output that exports activation key values.  I've updated the code in both the standard greenfield deployment (see the hcx_addon.tf file [here](https://github.com/Azure/Enterprise-Scale-for-AVS/tree/main/AVS-Landing-Zone/GreenField/Terraform)) or you can add the stand-alone module to your existing configuration. (see the avs_addon_hcx module folder [here](https://github.com/Azure/Enterprise-Scale-for-AVS/tree/main/terraform/modules/avs_addon_hcx).  Please let me know if you have any questions or issues or need additional configurations.   (cc @prasad3017 )

**Comment by jchancellor-ms** [comment]
Closing this issue based on the current release.  Please re-open if additional capabilities are required.
