### ISSUE TITLE
AVS Documentation Suggestion

### ISSUE THREAD

**Issue by brichbourg** [Azure/Enterprise-Scale-for-AVS#182]
I wanted to put this in as an issue since Prasad requested this, but here is the idea we came up with for grouping the AVS networking design options in a manner that we feel would be easier to consume and reference.
 
The main thing that stood out to us was where we wanted the firewall to be placed at.  Given that, we wondered if grouping the documentation in a manner where the firewall placement is the main focus would make a little more sense to customers and partners alike when they are trying to digest the various AVS network options.  That way people don’t have to remember what scenario 1, 2, 3, etc. is.  You can say “In the Azure NVA based design” and you automatically know what that person is referring to.
 
Here is the skeleton to what we were thinking:
 
Azure Firewall Base
-Recommended Design(s)
-Optional Bolt On / Change 1
-Optional Bolt On / Change 2
-Multi-Region Design / Considerations

Azure NVA Based
-Recommended Design(s)
-Optional Bolt On / Change 1
-Optional Bolt On / Change 2
-Multi-Region Design / Considerations

AVS Based
-Recommended Design(s)
-Optional Bolt On / Change 1
-Optional Bolt On / Change 2
-Multi-Region Design / Considerations

On Prem Option
-Recommended Design(s)
-Optional Bolt On / Change 1
-Optional Bolt On / Change 2
-Multi-Region Design / Considerations
 
 
The idea is to group the various options under where the main firewall appliance is located.  For example, in Azure Firewall Base, this would include the recommended design that you guys think meets most of the customer requirements and has the most pros vs cons.  Then under that, you have sub-sections where you can have various options or changes that could be considered if the requirements are slightly different (like Azure Firewall in VWAN vs Hub and Spoke VNET).  Then finally, there should be a section for this design where multi-region is taken into consideration.
 
Hopefully, this will be helpful as you guys continue to mature the AVS offering and documentation.

**Comment by prasad3017** [comment]
Thank you for raising the request with your valuable feedback.

@sblair01 Could you please help to take this forward.

**Comment by prasad3017** [comment]
Hello @sblair01  We have a internal user story for the same. 

Hello @brichbourg  We are making progress and hope you keep you updated in couple of weeks.

**Comment by sblair01** [comment]
Acknowledged. Draft page in landing zone content. Will link to it for review in Jan '23.

**Comment by brichbourg** [comment]
Awesome, sounds good!

**Comment by prasad3017** [comment]
@brichbourg  thank you for your time. Kindly review the docs and provide us feedback.

**Comment by prasad3017** [comment]
Hello @brichbourg  Resolving the issue but please feel free open if documentation does not meet the ask. Happy to work with you and team.

**Comment by sblair01** [comment]
Hey - we never shared the page with @brichbourg: https://github.com/Azure/Enterprise-Scale-for-AVS/blob/main/BrownField/Networking/Concepts/Connectivity-Single-region/Connectivity-Options-SingleRegion.md

Some images got broken along the way and pending a PR, but please look at this page, and the implmentations options referenced at the botton of the page, and let us know if this is going in the right direction.

**Comment by prasad3017** [comment]
Great call out @sblair01. I had a meeting with the team and shared the content 2 weeks ago. This helps too.
