### ISSUE TITLE
AVS A36PT not showing as a SKU

### ISSUE THREAD

**Issue by commissar117** [Azure/Enterprise-Scale-for-AVS#223]
![image](https://user-images.githubusercontent.com/60891797/221665935-cee2ed4e-5bc8-416d-bc3d-8167b592aca4.png)
![image](https://user-images.githubusercontent.com/60891797/221665984-c0478acd-6cd1-4f44-97ef-2549b6b2699c.png)
The SKUs are not matching between the GUI and the accelerator

**Comment by prasad3017** [comment]
@shaunjacob is looking to this.

**Comment by prasad3017** [comment]
#225  here is the PR to address the feedback. 

@commissar117  thank you for raising the feedback

**Comment by prasad3017** [comment]
@commissar117 kindly let me know if the new changes looks good.

**Comment by commissar117** [comment]
I already deployed from the GUI next project I will let you know. Thanks for jumping on this.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by prasad3017** [comment]
thank you and please feel free to reopen the issue.
