### ISSUE TITLE
Clarify what monitoring components the user gets when deploying Greenfield Deployment vs the Brownfield Monitoring Component

### ISSUE THREAD

**Issue by husamhilal** [Azure/Enterprise-Scale-for-AVS#231]
It might help customer distinguish when to use what? 

Another suggestion is to create a list of BOM, that shows everything that this repo contains.

**Comment by prasad3017** [comment]
@husamhilal  I would love to learn more on the BOM. 

Also, Greenfield and brownfield - I am meeting with Shaun this week to discuss the same. Would you like to participate?

@shaunjacob

**Comment by husamhilal** [comment]
> 

Sure, the idea of BOM is to help navigate the AVS ESLZ repo. We have great stuff, but sometimes users get lost in finding resources they are looking for. So, Bill of Material (BOM) (or simple Index page), might be helpful to create and maintain so new users can find what they are looking for.

This week I have a workshop that I'm presenting to one of our partners. But if the time permits and works with my schedule,  I'm happy to participate in the conversations 👍

**Comment by sblair01** [comment]
@husamhilal  on a semi-related note, still in progress but we have a wiki page. You navigate there by hitting the wiki link in the top right of the nav, or using the link below: 

https://github.com/Azure/Enterprise-Scale-For-AVS/wiki

I manually moved these pages there but working on automation to keep the pages up to date and in sync.

**Comment by prasad3017** [comment]
Thank you @sblair01 . Please suggest once completed

**Comment by prasad3017** [comment]
Hello Husam, this is being resolved in the release.

**Comment by husamhilal** [comment]
Thanks a lot Prasad, much appreciated 👍
