### ISSUE TITLE
AVS Networking Documentation spread across multiple locations

### ISSUE THREAD

**Issue by husamhilal** [Azure/Enterprise-Scale-for-AVS#233]
Centralize AVS Networking documentation in one location. Currently, they are spread across two locations as you see below:

<img width="468" alt="image" src="https://user-images.githubusercontent.com/11361105/225017808-17a99fa7-1855-4a9e-8d46-45d4ced9ec3c.png">

**Comment by prasad3017** [comment]
@khushal08 could you please take care of this?

**Comment by husamhilal** [comment]
<img width="316" alt="image" src="https://user-images.githubusercontent.com/11361105/225190060-03c1e6e3-4ea0-49ee-bc37-c8b2711e0ab2.png">

**Comment by prasad3017** [comment]
@khushal08 Could you please help to resolve this week?

**Comment by khushal08** [comment]
@prasad3017 I will move all Networking documents in a central location.

**Comment by sblair01** [comment]
Resolved. We will look to move the entire networking folder one level up in future iterations coming soon.
