### ISSUE TITLE
Add steps and clarify language in Enterprise-Scale-for-AVS/BrownField/Networking/Step-By-Step-Guides/Scenario-1/readme.md

### ISSUE THREAD

**Issue by StevePantol** [Azure/Enterprise-Scale-for-AVS#234]
While working through the Scenario 1 step-by-step guide to produce a video demonstrating the process, we identified a few necessary additions and suggestions for improvement. These include:

- Explain and demonstrate the need to create a Route Table with a default route with a next-hop of internet and apply it to the Application Gateway subnet, if the Application Subnet is in a VNet protected by Azure Firewall. See Solution Step 6 here: https://learn.microsoft.com/en-us/azure/application-gateway/application-gateway-backend-health-troubleshooting#backend-health-status-unknown
- Explain and demonstrate the need to create a network rule in the Firewall Policy to allow DNS resolution when the default NSX DNS Service is being used. Source: DNS Service IP, Protocol: UDP, Port 53, Destination: 1.1.1.1,1.0.0.1 (or preferred servers)
- Create a table up front listing all required subnets and sample IP space
- Minor formatting fixes throughout

I am working on a PR to address these.

In addition to the above, I would propose three additional changes:

- Deploy and use Azure Bastion to access the Jumpbox VM rather than opening up RDP and using a Route Table. We can demonstrate and can explain the Route Table concept as part of the AppGateway configuration
- Related to the above, add a note that we're creating the rule to allow RDP access into the VMs from a home office to demonstrate DNAT rules, and this is not a recommended configuration 
- Remove the NSX-T Network Segment creation portion. It's a long document already and this is duplicative--anyone that prefers the NSX-T experience already knows how to use it. :)

I'd like to hear some sort of go-ahead from somebody official before including these three items.

**Comment by sblair01** [comment]
Thanks @StevePantol - The changes suggested are reasonable (especially the bastion portion which is a best practice), so feel free to tag the PR here once completed. The author @MGodfrey50 is OOO this week, but myself @jasonamedina can take a look at the edits. 

The part that I need to review is the NSX-T segment. Agreed that it's a long doc, but many users are new to NSX and would prefer to have all the steps in one place vs googling around.

**Comment by prasad3017** [comment]
Thank you Steve.

**Comment by StevePantol** [comment]
https://github.com/Azure/Enterprise-Scale-for-AVS/pull/247

**Comment by prasad3017** [comment]
PR is in and under review - https://github.com/Azure/Enterprise-Scale-for-AVS/pull/247
