### ISSUE TITLE
Feature Request - Dashboard Update to support Azure VWAN Implementation

### ISSUE THREAD

**Issue by birdnathan** [Azure/Enterprise-Scale-for-AVS#241]
Current AVS Dashboard is only configured to support traditional hub/spoke expressroute connections. Suggest that they are updated to include support for those customers that use Virtual WAN for connectivity be it an [expressroute ](https://learn.microsoft.com/en-us/azure/virtual-wan/virtual-wan-expressroute-portal)or [vpn ](https://learn.microsoft.com/en-us/azure/azure-vmware/configure-site-to-site-vpn-gateway)

The metric namespaces are different when connectivity is provided by Virtual WAN.

e.g
<img width="291" alt="image" src="https://user-images.githubusercontent.com/42775203/228802132-f5272449-ff3a-43c8-8a98-a07a5b66c868.png">

<img width="225" alt="image" src="https://user-images.githubusercontent.com/42775203/228802557-15f7fdf3-4902-493a-b85a-9283477a7bc3.png">

There Terraform config also needs an update:
╷
│ Warning: Deprecated Resource
│
│   with azurerm_dashboard.avs-dashboard-primary,
│   on spoke.avs.monitoring.tf line 63, in resource "azurerm_dashboard" "avs-dashboard-primary":
│   63: resource "azurerm_dashboard" "avs-dashboard-primary" {
│
│ The `azurerm_dashboard` resource is deprecated and will be removed in v4.0 of the AzureRM Provider - the replacement is available as `azurerm_portal_dashboard`.
│
│ (and one more similar warning elsewhere)

**Comment by prasad3017** [comment]
@birdnathan  we are going look into this next week.

**Comment by jchancellor-ms** [comment]
@prasad3017 - I've submitted a pull request for the Terraform components.  I'll need to talk to Shaun to see if we can correct the dashboard for ARM/Bicep.

**Comment by prasad3017** [comment]
Thank you @birdnathan  hope you are able to try this in the new TF code. Please share the feedback.

**Comment by birdnathan** [comment]
> Thank you @birdnathan hope you are able to try this in the new TF code. Please share the feedback.

Sorry for delay in coming back to you @prasad3017 tested this today and all is good. Thanks for fixing.
