### ISSUE TITLE
Update hub and spoke step by steps

### ISSUE THREAD

**Issue by sblair01** [Azure/Enterprise-Scale-for-AVS#260]
https://github.com/Azure/Enterprise-Scale-for-AVS/tree/main/BrownField/Networking/Step-By-Step-Guides/Expressroute%20connectivity%20for%20AVS%20without%20Global%20Reach

1) Feedback that the image doesn't match the Azure docs so this scenario isn't easy to identify 
2) While cli is fine, the step-by-step needs screenshots from a portal experience so that it's easy to follow

3) The most important issue is that I have only seen this successfully implemented by specific members of the team and often requires their intervention to unblock users which do not scale. A simple mistake can lead to long amounts of troubleshooting. There are also undocumented steps and gotchas in the current implementation. There is feedback that we may also need additional UDRs in the hub for users not comfortable with routing within their NVA

I would suggest to unpublish the step-by-step, updating with portal mages, having the field test it, updating the guidance, and republishing it. 

I would update the Hub and Spoke (scenario v) with a portal experience and images consistent with Azure docs too. 

Thanks.

**Comment by prasad3017** [comment]
@sblair01  is this something you can help to fix it?

**Comment by prasad3017** [comment]
@sblair01  could you please look into this?

**Comment by sblair01** [comment]
Closing out for now.
