### ISSUE TITLE
Egress charges hop by hop

### ISSUE THREAD

**Issue by CCarroz** [Azure/Enterprise-Scale-for-AVS#263]
Team, 

Thanks for the content. Truly appreciate the work put in to pull this all together. 
Would it be possible to provide hop by hop egress charges associated with each design?  I ask as I have not seen any real calls out the egress costs occurred  as it pertains to a real AVS design, especially when we start to add things like shared services, inspection, multi region etc. to the design.  

One of my drivers around this request is that when we look at AWS, depending on our design/configuration, egress charges can get quite expensive quite quickly especially when we add things like inspection for all traffic to the design.  

Thank you for the support.

**Comment by prasad3017** [comment]
@khushal08  @fguerri  Could you please look into this and suggest a solution

**Comment by khushal08** [comment]
Hi @CCarroz, 
Are you suggesting we should have a cost section for each of our network designs? 
For example, one of the cost questions that you would like to be answered is, what points will I be charged for egress data? And how much?

**Comment by CCarroz** [comment]
Khushal, 

Correct, would love to see a breakdown of egress charges a client would incur for each design.  For instance, what would be the cost impact if a client mandated that all traffic between VNETs needed to be inspected vs, only internet traffic. Lets say we needed to support vsphere replication to a AVS SRM environment. What would be the egress charge impact if our set up forced replication traffic through a NVA for inspection vs some other means.  The request is rooted in some of the things I have seen in VMC environments where we have gone through grate lengths to force this kind of traffic or HCX NE/IX traffic through a internet uplink  vs the client's DX that would force traffic through TGW, through a inspections VPC(the traffic is encrypted so inspection can't really inspect anything), back to the TGW, then to the VMware vTGW to then finally get to the VMC SDDC. In this case we would be hit with $.08 per GiB. In other cases we would not be supporting inspection but since we still needed to go from DX to TGW to vTGW, we are looking at $.04 a Gb. at .04 a Gb and with 4TB of change in data needing to be replicated a day that is $160 a day and 58.4k a year. clearly a lot of change for zero value.  I know MS egress is cheaper but would love to see something more spec to work off of. Amazon does not provide much info on egress charges as well but VMware has provided this kind of details in blogs to work off of. 
https://www.gilles.cloud/2021/06/costs-analysis-for-data-transfer-via.html

Hope this makes sense.  Just trying to take any ambiguity out of the sales cycle. Not one likes getting hit with a bill that was unexpected.

**Comment by fguerri** [comment]
Thank you for the feedback! 

I am pushing updates to the "AVS Networking Basics" section that cover the billing rules for AVS and AVS managed circuits.

BR,
Federico

**Comment by prasad3017** [comment]
Thank you @fguerri  once you push the updates. Please update the issue.

**Comment by fguerri** [comment]
Pull request created: Fix #263 - Egress charges hop by hop by fguerri · Pull Request #267 · Azure/Enterprise-Scale-for-AVS (github.com)<https://github.com/Azure/Enterprise-Scale-for-AVS/pull/267>

It's pending approval 🙂
________________________________
