### ISSUE TITLE
Replace Orange/Blue/Green/Red boxes with real shapes inferring what that object is

### ISSUE THREAD

**Issue by husamhilal** [Azure/Enterprise-Scale-for-AVS#268]
Issue: 
Customer/partners are facing a difficulty, when looking at the diagrams, not knowing what each object represents

Suggestion solution:
Can you please update the diagrams listed at the following article 
https://github.com/Azure/Enterprise-Scale-for-AVS/blob/main/BrownField/Networking/Concepts/Nsx-Firewall-Patterns/README.md ?

It helps to replace Orange/Blue/Green/Red with real shapes inferring what that object is. 

For example with certain Icon/Shape/etc showing NSX-T tier-0, tier1, segment...

Thank you for the help!

**Comment by sblair01** [comment]
@husamhilal thanks for submitting. I would like to keep the diagrams aligned with engineering but do also see how the orange boxes could be ambiguous. Is it possible to keep a middle ground and just label the boxes as seen here?:

https://techcommunity.microsoft.com/t5/azure-migration-and/firewall-integration-in-azure-vmware-solution/ba-p/2254961

Thanks, 

Sabine

**Comment by husamhilal** [comment]
> @husamhilal thanks for submitting. I would like to keep the diagrams aligned with engineering but do also see how the orange boxes could be ambiguous. Is it possible to keep a middle ground and just label the boxes as seen here?:
> 
> https://techcommunity.microsoft.com/t5/azure-migration-and/firewall-integration-in-azure-vmware-solution/ba-p/2254961
> 
> Thanks,
> 
> Sabine

Thanks for looking at this @sblair01 !

Yes, labeling the boxes will be fine for the time being. At least, that will make it obvious what these boxes present from the first look without reading.
