### ISSUE TITLE
Monitoring Section Needs a ReadMe

### ISSUE THREAD

**Issue by sblair01** [Azure/Enterprise-Scale-for-AVS#270]
Ask: As a consumer of AVS Monitoring automation, I need to understand what I am deploying. There are no screenshots or explanation of the portal experience. At minimum, there should be links to this. 

Current Experience: Customer has to navigate to Brownfield Section which is not straightforward to find. They then have to click on each link in the monitoring section and review the Bicep or ARM. 

Ideal experience: 

1) Readme of why and how to use the automation with end result as a screenshot
2) [Optional] - Short video (10 mins or less) on how to deploy the monitoring.

**Comment by prasad3017** [comment]
@husamhilal Is this something you can help us?

**Comment by prasad3017** [comment]
@rybirk  could you please assist with this issue?

**Comment by sblair01** [comment]
@prasad3017 I also created a story: https://dev.azure.com/CSUSolEng/Accelerator%20-%20AVS/_workitems/edit/29183/

**Comment by husamhilal** [comment]
> @husamhilal Is this something you can help us?

Is help still needed?

If Yes, I can work on it. 

Please let me know.

**Comment by prasad3017** [comment]
Yes sir. Please help

**Comment by prasad3017** [comment]
@husamhilal hope all is well. Kindly let me know if we can close this in Aug 2023.

**Comment by michielvanschaik** [comment]
On the backlog.
