### ISSUE TITLE
FAQ section for HCX

### ISSUE THREAD

**Issue by sblair01** [Azure/Enterprise-Scale-for-AVS#272]
Ask: As a person in the field, I have frequently asked questions about HCX. It would be nice to find those questions quickly and point to them in the doc. 

Current behavior: During deliveries, I Often searching through docs on the fly that don't give a definitive answer or reach out to a specialist

Example questions include:

Can we keep HCX for the longer term? (e.g stretching networks and then letting the address live permanently after unstretching)
Can we keep HCX for DR?
Can we use SRM licensing? When to use SRM over HCX?
Are there risks of using HCX over VPN with public IP?

**Comment by prasad3017** [comment]
@sblair01 Please suggest if you can help to drive this along with @rcanton  @khensler

**Comment by CCarroz** [comment]
@sblair01, Just so I am clear. I sounds like you have your answers, but the request is to have those answers posted publicly so anyone could find it and reference?  Just wanted to check and make sure you had answers you needed.

**Comment by michielvanschaik** [comment]
@sblair01 Let us take his to the backlog.
