### ISSUE TITLE
Request:  NSX-T VPN Connectivity Guide 

### ISSUE THREAD

**Issue by jnordsving** [Azure/Enterprise-Scale-for-AVS#278]
I would like to see an SDDC-NSX-T to Onprem  (policy/route based) connectivity guide.  Since the SMB market may not have a need for Azure native resources and cost cutting on Azure vWAN/HUB runtime.

**Comment by prasad3017** [comment]
Thank you @jnordsving .  @khushal08  is this something you can help?

**Comment by sblair01** [comment]
@jnordsving -  sorry for the delay. Can you look here and let me know if this satisfies your request?: 

https://github.com/Azure/Enterprise-Scale-for-AVS/tree/main/BrownField/Networking/VPN-SDWAN

Thanks, 

sblair

**Comment by jnordsving** [comment]
Thanks for posting these updates.   I'll take a look here the next couple days.
