### ISSUE TITLE
New Compute Segment, allowing for on-prem communications

### ISSUE THREAD

**Issue by jnordsving** [Azure/Enterprise-Scale-for-AVS#279]
I created a new Compute Segment of 10.5.5.0/24 - GW - .1   this does not exist on premises.   I would like the VMs on this Segment to communicate with my on-premises VMs residing 10.89.20.0/24. -this network is where our VDI systems are running, & for access to AVS vCenter, & NSX-T. which is working perfectly through our VPN.

I've updated the VPN (policy based) with the new SDDC Compute Segment on both sides.  but yet no traffic is being passed.  
I have another test compute segment on the SDDC of 192.168.5.0/24,  which between the two segments I can ping the VMs. 
Next issue is,  I have internet out connectivity on the 192.168.5.x. network,  where my VMs on the 10.5.5.x segment are having problems getting internet out.  

Hopefully you can help me clear some of these issues up.

I've attached the compute segment screen capture configuration.  
<img width="1265" alt="Screenshot 2023-08-14 at 9 53 15 PM" src="https://github.com/Azure/Enterprise-Scale-for-AVS/assets/28025703/b853def1-148c-47ed-bdc1-235e0b00dcaf">

Also,  it would be great if you had a connectivity testing tab for running DNS/IP tests from within the Azure Portal.   See attached file..  this is from our VMware on AWS SDDC
<img width="1419" alt="Screenshot 2023-08-14 at 9 46 54 PM" src="https://github.com/Azure/Enterprise-Scale-for-AVS/assets/28025703/2f4d9c43-eb21-441f-9d97-531ca5462b87">

**Comment by michielvanschaik** [comment]
@fguerri Is this something you can help with?

**Comment by jnordsving** [comment]
Any help on this?

I created a new Compute Segment of 10.5.5.0/24 - GW - .1 this does not exist on premises. I would like the VMs on this Segment to communicate with my on-premises VMs residing 10.89.20.0/24. -this network is where our VDI systems are running, & for access to AVS vCenter, & NSX-T. which is working perfectly through our VPN.

I've updated the VPN (policy based) with the new SDDC Compute Segment on both sides. but yet no traffic is being passed. I have another test compute segment on the SDDC of 192.168.5.0/24, which between the two segments I can ping the VMs.

**Comment by husamhilal** [comment]
@michielvanschaik  I think we should device this into two asks: one is the troubleshooting part, I'm helping @jnordsving with that as we speak, and the feature request as he is asking for connectivity testing feature similar to VMC on AWS.
