### ISSUE TITLE
Add documentation covering the PaloAlto Cloud NGFW (SaaS) in Azure vWAN integration with AVS

### ISSUE THREAD

**Issue by husamhilal** [Azure/Enterprise-Scale-for-AVS#283]
We need to figure out if it's applicable or not? What's the limitation? etc....

**Comment by michielvanschaik** [comment]
@husamhilal  Can you look into this? Or let me know who is needed?

**Comment by husamhilal** [comment]
@michielvanschaik  I did reach out to PaloAlto to understand further. I will update once I hear back from them. Thanks!

**Comment by sblair01** [comment]
@husamhilal where are you looking for this documentation to live?

**Comment by husamhilal** [comment]
> @husamhilal where are you looking for this documentation to live?

Something like a section in the AVS LZA documentation (initially starting in this repo), talking about third party NVAs integration with AVS. That could be a double click on Network Design Guide from internet inbound/outbound inspection. It can be it's own page and we just link to it. 

Right now we have this, https://learn.microsoft.com/en-us/azure/virtual-wan/how-to-palo-alto-cloud-ngfw#known-limitations but a documentation in context of AVS could help!

**Comment by michielvanschaik** [comment]
Agree, I would propose a separate page on NVA integrations in the NDG. @husamhilal please update if you have response from PaloAlto.

**Comment by husamhilal** [comment]
I asked them specifically about Routing Intent, and they confirm that the the Cloud NGFW documentation on Microsoft Learn called out that limitations that apply to VWAN Routing Intent and Routing Policies also applies: https://learn.microsoft.com/en-us/azure/virtual-wan/how-to-palo-alto-cloud-ngfw#known-limitations
<img width="816" alt="image" src="https://github.com/Azure/Enterprise-Scale-for-AVS/assets/11361105/bfe6a3d9-2ffe-47ee-9b40-089b1e9f498d">

What I'm suggesting here is to contextualize the PaloAlto cloud NGFW with an AVS use case.

**Comment by sblair01** [comment]
cc @jasonamedina

**Comment by jasonamedina** [comment]
@husamhilal and @michielvanschaik, I have extensive experience with Palo Alto and I could work with @sblair01 on getting an Azure VMware Solution with Palo Alto SAAS use case out there. If we could get licensing I could even go as far as using the Panorama Integration.

**Comment by michielvanschaik** [comment]
@jasonamedina will add this to the backlog. Will look into the license part.

**Comment by husamhilal** [comment]
> @husamhilal and @michielvanschaik, I have extensive experience with Palo Alto and I could work with @sblair01 on getting an Azure VMware Solution with Palo Alto SAAS use case out there. If we could get licensing I could even go as far as using the Panorama Integration.

That would be great @jasonamedina ! Thank you very much!

**Comment by michielvanschaik** [comment]
Thank you @jasonamedina

**Comment by michielvanschaik** [comment]
@jasonamedina Victor will take this to the ADO board.

**Comment by vivalada** [comment]
This Issue will be now tracked in the ADO board.

**Comment by vivalada** [comment]
Blog post has been created and published: https://techcommunity.microsoft.com/t5/itops-talk-blog/azure-vmware-solution-with-vwan-routing-intent-and-palo-alto/ba-p/4062629.
