### ISSUE TITLE
AVS Internet Connectivity "ADD" Public IP failing.

### ISSUE THREAD

**Issue by jnordsving** [Azure/Enterprise-Scale-for-AVS#284]
See screen capture for the failure.  

<img width="1668" alt="Screenshot 2023-09-12 at 1 30 15 PM" src="https://github.com/Azure/Enterprise-Scale-for-AVS/assets/28025703/55caf88c-f142-48ba-8156-8523301a27ba">

**Comment by jnordsving** [comment]
This worked fine around a month ago in our tests, ended up deleting it since at the time there was not a need for the Public IPs.  Now we would like this for our VPN NST-T testing along with HCX.

**Comment by jnordsving** [comment]
Opened a MS Support Case:

Incident title:	AVS Internet Connectivity 'ADD' Public IP failing
Support request number:	2309120040015361
Severity rating:	B

**Comment by michielvanschaik** [comment]
Please update the status based on the outcome of the support case.

**Comment by jnordsving** [comment]
MS support is saying there is a broken process for "Internet connectivity" on the Azure Portal AVS page ,  they are working on an internal fix.   The workaround is using the CLI method.  

https://learn.microsoft.com/en-us/cli/azure/vmware/workload-network/public-ip?view=azure-cli-latest

which did work for us.

**Comment by michielvanschaik** [comment]
Thanks for sharing, and great that you are unblocked using the workaround.
