### ISSUE TITLE
HCX on-site appliance upgrades

### ISSUE THREAD

**Issue by patthiel455** [Azure/Enterprise-Scale-for-AVS#287]
I would like to recommend that there is an easy path to upgrade the HCX connectors as they are updated with additional features for both the cloud and the onsite appliance. It is important to make sure they are updated to the same level to reduce failures. Plus with the most updated versions patches and feature enhancements are then available for our customers to use.

**Comment by prasad3017** [comment]
@michielvanschaik  @khushal08  could you please check on this?

**Comment by michielvanschaik** [comment]
@khushal08 Can you follow up on this?

**Comment by khushal08** [comment]
Hi @patthiel455 Thanks for the feedback. Can you please elaborate on your comments? or point me to the easy path upgrade you mentioned?

**Comment by michielvanschaik** [comment]
Hi @patthiel455, can you please provide a link to the easy path to upgrade the HCX connectors?

**Comment by patthiel455** [comment]
https://docs.vmware.com/en/VMware-HCX/4.8/hcx-user-guide/GUID-02DB88E1-EC81-434B-9AE9-D100E427B31C.html#:~:text=Navigate%20to%20the%20Administration%20tab,receives%20the%20latest%20service%20update.



Pat Thiel



From: Michiel van Schaik ***@***.***>
Date: Thursday, December 14, 2023 at 2:38 AM
To: Azure/Enterprise-Scale-for-AVS ***@***.***>
Cc: Thiel, Pat ***@***.***>, Mention ***@***.***>
Subject: Re: [Azure/Enterprise-Scale-for-AVS] HCX on-site appliance upgrades (Issue #287)
External Message - Please be cautious when opening links or attachments in email


Hi @patthiel455<https://github.com/patthiel455>, can you please provide a link to the easy path to upgrade the HCX connectors?

**Comment by michielvanschaik** [comment]
Victor, please add this to the ADO board.

**Comment by vivalada** [comment]
This Issue will be now tracked in the ADO board.

**Comment by vivalada** [comment]
@patthiel455, there is already a page in the AVS documentation about how to upgrade HCX: https://learn.microsoft.com/en-us/azure/azure-vmware/upgrade-hcx-azure-vmware-solutions.
