### ISSUE TITLE
AVS Greenfield deployment is failing because of wrong Public IP type

### ISSUE THREAD

**Issue by starkilla2003** [Azure/Enterprise-Scale-for-AVS#290]
The deployment is not deploying a virtual network gateway because the following error:

"Basic IP configuration for ExpressRoute Virtual Network Gateways is not supported. Please create and associate a Standard IP. "

The deployment type used was the ARM deployment.

**Comment by demirsenturk** [comment]
Hello, would like to provide some information that may help identify the problem:
I noticed that there is a line in an ARM template (line 555) that specifies a Public IP with a Basic SKU.
```
                      "sku": {
                        "name": "Basic",
                        "tier": "Regional"
                      }
```
https://github.com/Azure/Enterprise-Scale-for-AVS/blob/82e3916925924290f3fa90a34683dbbb200f8a40/AVS-Landing-Zone/GreenField/ARM/ESLZDeploy.deploy.json#L555

This is used then in the deployment of the VNET Gateway with Standard SKU [parameters('GatewaySku')], which can lead to the above error.

```
                      "name": "[variables('GatewayName')]",
                      "location": "[parameters('Location')]",
                      "properties": {
                        "gatewayType": "ExpressRoute",
                        "sku": {
                          "name": "[parameters('GatewaySku')]",
                          "tier": "[parameters('GatewaySku')]"
                        },
                        "ipConfigurations": [
                          {
                            "name": "default",
                            "properties": {
                              "privateIPAllocationMethod": "Dynamic",
                              "subnet": {
                                "id": "[resourceId('Microsoft.Network/virtualNetworks/subnets', variables('VNetName'), 'GatewaySubnet')]"
                              },
                              "publicIPAddress": {
                                "id": "[resourceId('Microsoft.Network/publicIPAddresses', format('{0}-PIP', variables('GatewayName')))]"
                              }
```

https://github.com/Azure/Enterprise-Scale-for-AVS/blob/82e3916925924290f3fa90a34683dbbb200f8a40/AVS-Landing-Zone/GreenField/ARM/ESLZDeploy.deploy.json#L580C31-L580C31

**Comment by starkilla2003** [comment]
The issue seems to also be present in the Bicep part of the Greenfield deployment. Also when changing the SKU to Standard the IP also needs to be static.

**Comment by husamhilal** [comment]
Thanks a lot @starkilla2003 and @demirsenturk for detecting this issue. You are 100% correct. This is a recent change in Azure as you see here: https://learn.microsoft.com/en-us/azure/expressroute/expressroute-howto-add-gateway-portal-resource-manager

![image](https://github.com/Azure/Enterprise-Scale-for-AVS/assets/11361105/1dbf2d64-c4f7-43d9-bcab-c8b3043bc98a)

I will make sure to fix this problem.

cc: @michielvanschaik, @sblair01 
please see this pull request: https://github.com/Azure/Enterprise-Scale-for-AVS/pull/291

**Comment by michielvanschaik** [comment]
Thank you @starkilla2003 and @demirsenturk for detecting the issue and @husamhilal for creating the pull request.

cc: @sblair01

**Comment by husamhilal** [comment]
Perfect, thanks @michielvanschaik!

@starkilla2003, @demirsenturk as your time permits, can you confirm that this change addressed your concern?

Also, please feel free to provide any addition feedback for issues or new features. We're happy to improve the AVS LZA 🙂

**Comment by starkilla2003** [comment]
@husamhilal everything works as expected now! thank you for your effort!
