### ISSUE TITLE
Update VPN guidance

### ISSUE THREAD

**Issue by sblair01** [Azure/Enterprise-Scale-for-AVS#297]
Hi. Can we update the documentation to explain the MTU settings?:
The Github says 1300 but Azure Docs says 1350: 

https://learn.microsoft.com/en-us/azure/azure-vmware/configure-vmware-hcx#create-network-profiles
https://github.com/Azure/Enterprise-Scale-for-AVS/blob/main/hcx/hcx-deployment.md#vmware-hcx-over-vpn

Can we explain when to set it to which? Also, can we recommend enabling WAN optimization?

Thanks, 

Sabine

**Comment by vivalada** [comment]
@rcanton Could you assist on this issue?

**Comment by riperez123** [comment]
This all depends. 
1300 MTU is a very safe MTU to recommend. 
1350 will work in most cases. 

I typically go with 1300 MTU to be on the safe side.  I am cautious by nature so this is why I recommend this setting. 
Customers should verify their MTU setting by using an MTU tool to discover the MTU setting for their network. 

I think we should streamline it across our documentation to either 1300 or 1350 MTU. Or word it as 1300 MTU is a safe MTU to set it at but 1350 MTU will work in most cases, verify your MTU setting by using an MTU tool...

**Comment by vivalada** [comment]
Solved the issue in the PR #300
