### ISSUE TITLE
Feature Request - Private Cloud to Private Cloud Connectivity Diagnostics

### ISSUE THREAD

**Issue by birdnathan** [Azure/Enterprise-Scale-for-AVS#309]
Is there anyway you can add monitoring capabilities to your Dashboard to export metrics for traffic between AVS private clouds in differnt regions (connected via GlobalReach). So the connections between 2 AVS managed expressroutes? Im unsure if microsoft expose this metric anywhere.

**Comment by birdnathan** [comment]
@maheshbenke Yes i think that would work

**Comment by michielvanschaik** [comment]
@vivalada Let us add this as a User Story to the ADO board.

**Comment by birdnathan** [comment]
This was closed but we cant see User Stories in ADO, so is this still planned? @michielvanschaik @maheshbenke
