### ISSUE TITLE
Monitoring Deployment fails

### ISSUE THREAD

**Issue by vcdx71** [Azure/Enterprise-Scale-for-AVS#314]
The monitoring component when doing the Greenfield deployment is failing to deploy with the following error:

{"code":"DeploymentFailed","target":"/subscriptions/xxxxxx/providers/Microsoft.Resources/deployments/AVS-tmekt3hzpov2a-Monitoring","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"InvalidTemplate","message":"Deployment template validation failed: 'The resource 'Microsoft.Insights/metricAlerts/mike-sddc-CPU' at line '1' and column '2807' is defined multiple times in a template. Please see https://aka.ms/arm-syntax-resources for usage details.'.","additionalInfo":[{"type":"TemplateViolation","info":{"lineNumber":1,"linePosition":2807,"path":"properties.template.resources[0]"}}]}]}

Greenfield lite deployed.

**Comment by michielvanschaik** [comment]
@vivalada Can you please take a look at this issue?

**Comment by vivalada** [comment]
Sure, @michielvanschaik.

**Comment by vivalada** [comment]
Issue was solved on PR #327.
