### ISSUE TITLE
HCX w/ PC errors

### ISSUE THREAD

**Issue by Trevor-Davis** [Azure/Enterprise-Scale-for-AVS#59]
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/56545070/140802129-81fcb8ea-76ee-4dfc-a3de-43afcbed1b09.png)
receive this error when using the private cloud w/ HCX template.

**Comment by ScottHolden** [comment]
I'll have a look at this today for you.

**Comment by prasad3017** [comment]
Hello Trevor, We will be providing update soon on this. 
@ScottHolden

**Comment by ScottHolden** [comment]
Closing as duplicate of #63, this has been raised with engineering.
