### ISSUE TITLE
[Documentation] Expand documentation on Single region deployment

### ISSUE THREAD

**Issue by prasad3017** [Azure/Enterprise-Scale-for-AVS#60]
Single Region deployment currently does not provide description or definition about each of the component being deployed part of the automation.

Kindly assist to add the details.

**Comment by prasad3017** [comment]
@Mahesh-MSFT Looking for your help in this regard

**Comment by Mahesh-MSFT** [comment]
this is tracked via this [pr](https://github.com/Azure/Enterprise-Scale-for-AVS/pull/64).
