### ISSUE TITLE
Installing AVS via Automation with an existing Azure native environment

### ISSUE THREAD

**Issue by kjellow** [Azure/Enterprise-Scale-for-AVS#61]
Hi Team,

I tested the AVS automation and it works very well as expected. However, this was deployed with a new Azure nework configuration (vNet, GW, and all RGs). Since most customers already have an Azure envirnment how woud we go about deloying to that exiting environment using the Automation process?

Thanks

Kevin

**Comment by prasad3017** [comment]
Thanks Kevin. We will update in this regard. Ack the request
@sonmitt --> Kindly review

**Comment by sonmitt** [comment]
Hi @kjellow,
There are individual modules as well in case of existing resources which customer can use for deploying a specific scenario (link below) as fit for their requirement using Automation.
[https://github.com/Azure/Enterprise-Scale-for-AVS/tree/main/Scenarios#avs-networking]

Give it a try and let us know if you face any issue.

**Comment by prasad3017** [comment]
@kjellow  We will be resovling this and please feel free to reopen the issue if issue still persists.
