### ISSUE TITLE
Clarify jumphost requirement pertaining to cost

### ISSUE THREAD

**Issue by lamw** [Azure/Enterprise-Scale-for-AVS#62]
I noticed in the Azure Template, it mentions deploying a bastion (Jumphost), it wasn't clear to me on whether this is something that is provided for free as part of using the template OR if there is a cost for end users? It would be useful to add some details around that and how its used (e.g. only required for the initial setup and can be deleted and hence cost or use of resources is time bound)

**Comment by prasad3017** [comment]
Thanks so much @lamw . We are checking in this regard.

**Comment by prasad3017** [comment]
Hello @lamw 

Jumpbox and Bastion are charged for the customers. We will update our the documentation to reflect the same
