### ISSUE TITLE
HCX ARM Issue

### ISSUE THREAD

**Issue by Trevor-Davis** [Azure/Enterprise-Scale-for-AVS#63]
![image](https://user-images.githubusercontent.com/56545070/143150457-49f1d415-07c8-4372-aa06-f72fbb142597.png)
this error pops when using the AVS Private Cloud w/ the HCX addon ARM template.

**Comment by ScottHolden** [comment]
This looks to be a bug in the resource provider (within the validation logic), the arm calls match the rest api specs that have been published. Let me raise this with engineering directly.

(Duplicate of #59 )

**Comment by Trevor-Davis** [comment]
Yeah, it's odd.  When I use the ARM template to just add HCX to an existing private cloud, works perfect.


Trevor Davis, Global Black Belt - Azure VMware Solution
954.854.2362  |  ***@***.******@***.***>
***@***.***

**Comment by poomnupong** [comment]
+1 with @Trevor-Davis.
My test - enable HCX on existing AVS - complete successfully without error.
