### ISSUE TITLE
Alert Email field in SingleRegion doesn't accept string

### ISSUE THREAD

**Issue by poomnupong** [Azure/Enterprise-Scale-for-AVS#66]
Most users will simply input email string in this field, especially those who are not familiar with ARM/JSON.
with email string in the field, portal UI will give error - Unable to parse the value into type 'array' - and validation will fail.

Correct format is ["user@company.com"] - with bracket.

**Comment by poomnupong** [comment]
Simple fix could be adding to the comment:
"Email addresses to be added to the alerting action group in JSON array format e.g. ["user@company.com"] "

Or accept string param and add it to array inside the template.

**Comment by ScottHolden** [comment]
Hey, I'll add some logic to accept a string and detect if it is an array or a single value, then update the param description.

**Comment by ScottHolden** [comment]
I've suggested a change in #67 that takes in a string, either a single email or a comma separated list (and an updated description). Would this make things simpler @poomnupong ?

**Comment by poomnupong** [comment]
Thanks, Scott. I could confirm the change on Service Health Alert and could confirm the description and comma-separated list of email pass validation. It's now less ambiguous and prescriptive.

This issue was originally target at SingleRegion but I agree to close this one as we now have the fixed code.
