### ISSUE TITLE
Alert email validation issue

### ISSUE THREAD

**Issue by Mahesh-MSFT** [Azure/Enterprise-Scale-for-AVS#80]
If I enter my email address in the "Alert Emails" box, then i get following error.

![image](https://user-images.githubusercontent.com/20776028/149776615-d7258a43-382e-4ac4-9bef-77f97382e8cd.png)

**Comment by prasad3017** [comment]
There is PR in place for this which is being reviewed by Scott Holden

**Comment by prasad3017** [comment]
This is fixed so resolving the issue #81
