### ISSUE TITLE
Default deployment's name causes race condition when launching simultaneously deployments

### ISSUE THREAD

**Issue by E-G-C** [Azure/Enterprise-Scale-for-AVS#89]
**Assumption**
No custom deployment name is specified via the `-n` or `--name` parameter when issuing the `az deployment` command.

**Scenario** 
When launching a deployment via cli/ARM template, the deployment’s default name is set to the deployment's filename i.e: `ESLZDeploy.deploy`

**Situation** 
When launching multiple deployments simultaneously, based on the assumption (see above). These deployments will try to use the same deployment name (deployment's filename) for each, creating a race condition.

**Result**
Only one deployment will succeed in being initiated with the subsequent deployments failing with the message: 

```json
{
    'code': 'DeploymentActive', 
    'message': "Unable to edit or replace deployment 'ESLZDeploy.deploy': previous deployment from '2/20/2022 3:06:18 PM' is   still active (expiration time is '2/27/2022 3:06:13 PM'). Please see https://aka.ms/arm-deploy for usage details."
}
```
**Suggestion**
Set the deployment name value in the ARM template, avoiding the default behavior.  It could be set to something like `desired prefix + datetime stamp` and dd a brief note in the documentation mentioning how the deployment’s default name is composed and how to change it via the cli parameter `--name -n`
Point the user for more details to:
https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/deploy-cli#azure-deployment-template-name

**Comment by prasad3017** [comment]
Thanks for raising this @E-G-C 

Looking into this

**Comment by sonmitt** [comment]
AZ CLI command for Greenfield deployment : _az deployment sub create -l AustraliaEast -c -f "ESLZDeploy.deploy.json" -p "@ESLZDeploy.parameters.json"_ - **This works fine for a single deployment at the subscription level.**

However, it is true that in the absence of unique deployment name in the Az Cli command when someone triggers multiple concurrent deployments in the same subscription/RG it will error out. 

@E-G-C , We will check and update the command and readme with appropriate fixes to resolve the issue for multiple deployments.

**Comment by sonmitt** [comment]
This issue has been fixed now. Documentation and AZ CLI command for Bicep and ARM is updated to include unique deployment name when running multiple deployments.
