### ISSUE TITLE
Location/Region in Automation

### ISSUE THREAD

**Issue by rallegroms** [Azure/Enterprise-Scale-for-AVS#98]
Can we consolidate these 2 required parameters inside of the automation template for greenfield deployment?
<img width="718" alt="image" src="https://user-images.githubusercontent.com/35306641/156603879-4d1e2e32-39cb-445f-9e86-a3d8eca47bca.png">

**Comment by sonmitt** [comment]
Thanks Robert for raising this. We are aware and already have a PR submitted to remove location parameter from the template. We will fix this soon.

**Comment by rallegroms** [comment]
Thank you @sonmitt. Closing issue.
